### ISSUE TITLE
Method of normalisation 

### ISSUE THREAD

**Issue by adithya8** [yqf3139/Activity-Recognition-from-Single-Chest-Mounted-Accelerometer#1]
Why did you chose this method of normalisation as you have neither implemented the standard normalisation techniques such as the minimax or 0-mean normalisation. Could you please explain why ?

**Comment by yqf3139** [comment]
Hi. I think I tried minmax but the method I used works slightly better.
I choose the ratio of all the signal to the min mean of the three signals. If using minmax, there may be some outlier points. You can have a try using min mean and max mean of three signals.

**Comment by adithya8** [comment]
Thank you. I'll look into what you told.
